-- Supabase SQL Editor에서 실행

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  student_id text not null,
  student_name text not null,
  score integer not null check (score >= 0 and score <= 100),
  subject text not null default '형상모델링검토',
  submitted_at timestamptz not null default now()
);

create index if not exists quiz_scores_subject_idx on public.quiz_scores (subject);
create index if not exists quiz_scores_student_id_idx on public.quiz_scores (student_id);

alter table public.quiz_scores enable row level security;

-- 서버(Vercel)는 service_role 키로 삽입하므로 RLS는 anon 사용자만 차단합니다.
-- Table Editor에서 직접 보시려면 대시보드에서 service role 또는 테이블 UI를 사용하세요.
